### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

arr = np.random.rand(50)

print(np.average(arr))
print(np.std(arr))


0.5079035022459674
0.29768122222967236


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arra = np.random.rand(10)

print(arra)
for arra in arra:
  if arra <= 0.5:
    arra = arra
    print(np.sqrt(arra))
  


[0.5621866  0.54166752 0.29698997 0.06938987 0.35800036 0.01678133
 0.27298913 0.89577095 0.23509764 0.88219891]
0.544967857898399
0.26341956487075463
0.5983313091061971
0.12954275861330872
0.5224836204195212
0.484868680106668


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
import numpy as np

matriz_3d = np.random.rand(3,3,3)

max_linha2 = np.amax(matriz_3d, axis=1)

print("Valor de cada linha \n", matriz_3d)
print("Valor máximo de cada linha",max_linha2)

Valor de cada linha 
 [[[0.2863723  0.05204168 0.78380852]
  [0.18876611 0.39983563 0.45862549]
  [0.05523305 0.53715899 0.97625414]]

 [[0.48833792 0.87277768 0.18774349]
  [0.85334709 0.75865048 0.21983584]
  [0.95424508 0.97813272 0.19864382]]

 [[0.63374415 0.60098914 0.86839897]
  [0.9016935  0.0403067  0.94756763]
  [0.02226488 0.0323281  0.02622102]]]
Valor máximo de cada linha [[0.2863723  0.53715899 0.97625414]
 [0.95424508 0.97813272 0.21983584]
 [0.9016935  0.60098914 0.94756763]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
import numpy as np


#axis = 1 --> Linha
#axis = 0 --> Coluna
matriz_5 = np.random.rand(5,5)
 
media = np.average(matriz_5, axis = 1)
sub_media = matriz_5 - media[:, np.newaxis]

print("Matriz", matriz_5)
print("Média de cada linha", media)
print("Subtração da média de cada linha", sub_media)



Matriz [[0.30121696 0.42933035 0.33983605 0.8344978  0.86020907]
 [0.65473592 0.10020633 0.49353755 0.45307467 0.91635666]
 [0.83250578 0.55233757 0.78091681 0.34340921 0.77344093]
 [0.98935243 0.03661345 0.24974028 0.45991598 0.67247927]
 [0.09325758 0.83513473 0.06629591 0.13631077 0.16159629]]
Média de cada linha [0.55301804 0.52358223 0.65652206 0.48162028 0.25851906]
Subtração da média de cada linha [[-0.25180108 -0.1236877  -0.213182    0.28147975  0.30719102]
 [ 0.13115369 -0.42337589 -0.03004468 -0.07050755  0.39277443]
 [ 0.17598372 -0.10418449  0.12439475 -0.31311285  0.11691887]
 [ 0.50773214 -0.44500683 -0.23188    -0.0217043   0.19085899]
 [-0.16526147  0.57661568 -0.19222315 -0.12220828 -0.09692277]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np 
 
matriz_4 = np.random.rand(4,4)

diagonais_matriz = np.diag(matriz_4)
media_matriz4 = np.average(diagonais_matriz)
desvio_matriz4 = np.std(diagonais_matriz)

print("Matriz 4x4 \n",matriz_4)
print("Diagonais da matriz \n", diagonais_matriz)
print("Media das diagonais da matriz \n", media_matriz4)
print("Desvio padrão das diagonais da matriz \n ", desvio_matriz4)



Matriz 4x4 
 [[0.23894137 0.54587598 0.049786   0.41025304]
 [0.93680248 0.50875537 0.46463311 0.36784341]
 [0.6104856  0.31417402 0.94868374 0.91226281]
 [0.73788939 0.46033881 0.92488727 0.73501381]]
Diagonais da matriz 
 [0.23894137 0.50875537 0.94868374 0.73501381]
Media das diagonais da matriz 
 0.6078485709704443
Desvio padrão das diagonais da matriz 
  0.26374779230555795
